n = str(input('Digite algo: '))
print('Abaixo segue informações sobre o que foi digitado')
print('O tipo primitivo é', type(n))
print('So tem espaços?', n.isspace())
print('É Um numero ?', n.isnumeric())
print('É Uma alfanumerico?', n.isalnum())
print('É alfabético?', n.isalpha())
print('É maiusculo?', n.isupper())
print('É Minusculo?', n.islower())
print('Esta capitalizada?', n.istitle())
